type Query {
    defaultEngineLevel: Int!
    validateMove(fen: String!, move: String!): MoveStatus!
    suggestMove(fen: String!, engineLevel: Int): MoveStatus!
}

interface Status {
    success: Boolean!
    message: String!
}

type StandardStatus implements Status {
    success: Boolean!
    message: String!
}

type MoveStatus implements Status {
    move: String
    newFen: String
    success: Boolean!
    message: String!
}
